### PR TITLE
US-015 Student Functionality

### PR DESCRIPTION
**Pull request by mustafacihat**
I created student entity and provided several service methods.

### CODE REVIEW

**Review by Nora85 — APPROVED** [review]

**Review by karamanesranur — COMMENTED** [review]
Good Job!

**Comment by denispupkov** [comment]
I will review soon

**Review by karamanesranur — APPROVED** [review]
Good Job

**Review by denispupkov — APPROVED** [review]
Got it!

**Comment by denispupkov** [comment]
Please merge

**Pull request merged**
