### PR TITLE
US-015 Student Functionality

### PR DESCRIPTION
**Pull request by Nora85**
I created studententity.

### CODE REVIEW

**Review by sulkemref — COMMENTED** [review]
Excellent!

**Comment by HasanainAlameen** [comment]
You have done a great job, Keep it up!

**Comment by HasanainAlameen** [comment]
Great job, keep it up!

**Review by denispupkov — APPROVED** [review]
Great job Kemal!

**Review by denispupkov — APPROVED** [review]
Looks good

**Review by denispupkov — APPROVED** [review]
Finally it works!

**Review by denispupkov — APPROVED** [review]
Well Done!

**Review by denispupkov — APPROVED** [review]
Great!

**Review by sulkemref — APPROVED** [review]
Good job!

**Pull request merged**
